--@Autor: Karina Flores García 
--@Autor: Alejandro Herrera Gandarela
--@Fecha creación: 23/12/2021
--@Descripción: DDL para sitio N2
p
rompt Creando tablas para el sitio N3 en AHGBDD_S1

create or replace procedure drop_table_if_exists(name in varchar2) is
	v_count number;
begin
	select count(*) 
	into v_count 
	from all_tables 
	where table_name = name;
	
	if (v_count > 0) then
       		execute immediate 'drop table ' || name || ' cascade constraints';
	end if;
end;
/

declare
    v_status_laptop varchar2(30) 	            := 'STATUS_LAPTOP';
    v_historico_status_laptop_f2_ahg_s1 varchar2(30) := 'HISTORICO_STATUS_LAPTOP_F1_AHG_S1';
    v_tipo_procesador_r_ahg_s1 varchar2(30)     := 'TIPO_PROCESADOR_R_AHG_S1';
	v_tipo_tarjeta_video_r_ahg_s1 varchar2(30)	:= 'TIPO_TARJETA_VIDEO_R_AHG_S1';
	v_tipo_almacenamiento_r_ahg_s1 varchar2(30) := 'TIPO_ALMACENAMIENTO_R_AHG_S1';
	v_tipo_monitor_r_ahg_s1 varchar2(30)	    := 'TIPO_MONITOR_R_AHG_S1';
	v_laptop_f2_ahg_s1 varchar2(30) 	        := 'LAPTOP_F2_AHG_S1';
    v_laptop_inventario_f2_ahg_s1 varchar2(30)  := 'LAPTOP_INVENTARIO_F2_AHG_S1';
    v_sucursal_f1_ahg_s1 varchar2(30) 	        := 'SUCURSAL_F1_AHG_S1';
	v_sucursal_taller_f1_ahg_s1 varchar2(30) 	:= 'SUCURSAL_TALLER_F1_AHG_S1';
    v_sucursal_venta_f1_ahg_s1 varchar2(30) 	:= 'SUCURSAL_VENTA_F1_AHG_S1';
    v_servicio_laptop_f1_ahg_s1 varchar2(30) 	:= 'SERVICIO_LAPTOP_F1_AHG_S1';
begin
	drop_table_if_exists(v_status_laptop);
	drop_table_if_exists(v_historico_status_laptop_f2_ahg_s1);
	drop_table_if_exists(v_tipo_procesador_r_ahg_s1);
	drop_table_if_exists(v_tipo_tarjeta_video_r_ahg_s1);
	drop_table_if_exists(v_tipo_almacenamiento_r_ahg_s1);
	drop_table_if_exists(v_tipo_monitor_r_ahg_s1);
	drop_table_if_exists(v_laptop_f2_ahg_s1);
	drop_table_if_exists(v_laptop_inventario_f2_ahg_s1);
    drop_table_if_exists(v_sucursal_f1_ahg_s1);
    drop_table_if_exists(v_sucursal_taller_f1_ahg_s1);
    drop_table_if_exists(v_sucursal_venta_f1_ahg_s1);
    drop_table_if_exists(v_servicio_laptop_f1_ahg_s1);
/


CREATE TABLE STATUS_LAPTOP(
    STATUS_LAPTOP_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE               VARCHAR2(40)     NOT NULL,
    DESCRIPCION         VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (STATUS_LAPTOP_ID)
)
;



-- 
-- TABLE: HISTORICO_STATUS_LAPTOP_F2_AHG_S1 
--

CREATE TABLE HISTORICO_STATUS_LAPTOP_F2_AHG_S1(
    HISTORICO_STATUS_LAPTOP_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS                  TIMESTAMP(6)     NOT NULL,
    STATUS_LAPTOP_ID              NUMBER(5, 0)     NOT NULL,
    LAPTOP_ID                     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (HISTORICO_STATUS_LAPTOP_ID), 
    CONSTRAINT RefSTATUS_LAPTOP8 FOREIGN KEY (STATUS_LAPTOP_ID)
    REFERENCES STATUS_LAPTOP(STATUS_LAPTOP_ID)
)
;



-- 
-- TABLE: TIPO_PROCESADOR_R_AHG_S1 
--

CREATE TABLE TIPO_PROCESADOR_R_AHG_S1(
    TIPO_PROCESADOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (TIPO_PROCESADOR_ID)
)
;



-- 
-- TABLE: TIPO_TARJETA_VIDEO_R_AHG_S1 
--

CREATE TABLE TIPO_TARJETA_VIDEO_R_AHG_S1(
    TIPO_TARJETA_VIDEO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                    VARCHAR2(40)     NOT NULL,
    DESCRIPCION              VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK11 PRIMARY KEY (TIPO_TARJETA_VIDEO_ID)
)
;



-- 
-- TABLE: TIPO_ALMACENAMIENTO_R_AHG_S1 
--

CREATE TABLE TIPO_ALMACENAMIENTO_R_AHG_S1(
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                     VARCHAR2(40)     NOT NULL,
    DESCRIPCION               VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (TIPO_ALMACENAMIENTO_ID)
)
;



-- 
-- TABLE: TIPO_MONITOR_R_AHG_S1 
--

CREATE TABLE TIPO_MONITOR_R_AHG_S1(
    TIPO_MONITOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE              VARCHAR2(40)     NOT NULL,
    DESCRIPCION        VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK13 PRIMARY KEY (TIPO_MONITOR_ID)
)
;



-- 
-- TABLE: LAPTOP_F2_AHG_S1 
--

CREATE TABLE LAPTOP_F2_AHG_S1(
    LAPTOP_ID                 NUMBER(10, 0)     NOT NULL,
    LAPTOP_REEMPLAZO_ID       NUMBER(10, 0),
    NUM_SERIE                 VARCHAR2(18)      NOT NULL,
    CANTIDAD_RAM              NUMBER(6, 0),
    CARACTERISTICAS_EXTRAS    VARCHAR2(2000)    NOT NULL,
    TIPO_PROCESADOR_ID        NUMBER(5, 0)      NOT NULL,
    TIPO_TARJETA_VIDEO_ID     NUMBER(5, 0)      NOT NULL,
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)      NOT NULL,
    TIPO_MONITOR_ID           NUMBER(5, 0)      NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (LAPTOP_ID), 
    CONSTRAINT RefTIPO_PROCESADOR_R_AHG_S118 FOREIGN KEY (TIPO_PROCESADOR_ID)
    REFERENCES TIPO_PROCESADOR_R_AHG_S1(TIPO_PROCESADOR_ID),
    CONSTRAINT RefTIPO_TARJETA_VIDEO_R_AHG_19 FOREIGN KEY (TIPO_TARJETA_VIDEO_ID)
    REFERENCES TIPO_TARJETA_VIDEO_R_AHG_S1(TIPO_TARJETA_VIDEO_ID),
    CONSTRAINT RefTIPO_ALMACENAMIENTO_R_AHG20 FOREIGN KEY (TIPO_ALMACENAMIENTO_ID)
    REFERENCES TIPO_ALMACENAMIENTO_R_AHG_S1(TIPO_ALMACENAMIENTO_ID),
    CONSTRAINT RefTIPO_MONITOR_R_AHG_S121 FOREIGN KEY (TIPO_MONITOR_ID)
    REFERENCES TIPO_MONITOR_R_AHG_S1(TIPO_MONITOR_ID)
)
;



-- 
-- TABLE: LAPTOP_INVENTARIO_F2_AHG_S1 
--

CREATE TABLE LAPTOP_INVENTARIO_F2_AHG_S1(
    LAPTOP_ID           NUMBER(10, 0)    NOT NULL,
    SUCURSAL_ID         NUMBER(10, 0),
    FECHA_STATUS        TIMESTAMP(6)     NOT NULL,
    STATUS_LAPTOP_ID    NUMBER(5, 0)     NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (LAPTOP_ID), 
    CONSTRAINT RefSTATUS_LAPTOP9 FOREIGN KEY (STATUS_LAPTOP_ID)
    REFERENCES STATUS_LAPTOP(STATUS_LAPTOP_ID)
)
;



-- 
-- TABLE: SUCURSAL_F1_AHG_S1 
--

CREATE TABLE SUCURSAL_F1_AHG_S1(
    SUCURSAL_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(10)     NOT NULL,
    ES_TALLER      NUMBER(1, 0)     NOT NULL,
    ES_VENTA       NUMBER(1, 0)     NOT NULL,
    NOMBRE         VARCHAR2(40)     NOT NULL,
    LATITUD        BINARY_FLOAT     NOT NULL,
    LONGITUD       BINARY_FLOAT     NOT NULL,
    URL            VARCHAR2(200)    NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (SUCURSAL_ID)
)
;



-- 
-- TABLE: SUCURSAL_TALLER_F1_AHG_S1 
--

CREATE TABLE SUCURSAL_TALLER_F1_AHG_S1(
    SUCURSAL_ID          NUMBER(10, 0)    NOT NULL,
    DIA_DESCANSO         NUMBER(1, 0)     NOT NULL,
    TELEFONO_ATENCION    VARCHAR2(20)     NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (SUCURSAL_ID), 
    CONSTRAINT RefSUCURSAL_F1_AHG_S13 FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F1_AHG_S1(SUCURSAL_ID)
)
;



-- 
-- TABLE: SERVICIO_LAPTOP_F1_AHG_S1 
--

CREATE TABLE SERVICIO_LAPTOP_F1_AHG_S1(
    NUM_SERVICIO    NUMBER(10, 0)     NOT NULL,
    LAPTOP_ID       NUMBER(10, 0)     NOT NULL,
    IMPORTE         NUMBER(8, 2)      NOT NULL,
    DIAGNOSTICO     VARCHAR2(2000)    NOT NULL,
    FACTURA         BLOB,
    SUCURSAL_ID     NUMBER(10, 0)     NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (NUM_SERVICIO, LAPTOP_ID), 
    CONSTRAINT RefSUCURSAL_TALLER_F1_AHG_S117 FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_TALLER_F1_AHG_S1(SUCURSAL_ID)
)
;



-- 
-- TABLE: SUCURSAL_VENTA_F1_AHG_S1 
--

CREATE TABLE SUCURSAL_VENTA_F1_AHG_S1(
    SUCURSAL_ID      NUMBER(10, 0)    NOT NULL,
    HORA_APERTURA    DATE             NOT NULL,
    HORA_CIERRE      DATE             NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (SUCURSAL_ID), 
    CONSTRAINT RefSUCURSAL_F1_AHG_S15 FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F1_AHG_S1(SUCURSAL_ID)
)
;



-- 
-- INDEX: Ref78 
--

CREATE INDEX Ref78 ON HISTORICO_STATUS_LAPTOP_F2_AHG_S1(STATUS_LAPTOP_ID)
;
-- 
-- INDEX: Ref918 
--

CREATE INDEX Ref918 ON LAPTOP_F2_AHG_S1(TIPO_PROCESADOR_ID)
;
-- 
-- INDEX: Ref1119 
--

CREATE INDEX Ref1119 ON LAPTOP_F2_AHG_S1(TIPO_TARJETA_VIDEO_ID)
;
-- 
-- INDEX: Ref1220 
--

CREATE INDEX Ref1220 ON LAPTOP_F2_AHG_S1(TIPO_ALMACENAMIENTO_ID)
;
-- 
-- INDEX: Ref1321 
--

CREATE INDEX Ref1321 ON LAPTOP_F2_AHG_S1(TIPO_MONITOR_ID)
;
-- 
-- INDEX: Ref79 
--

CREATE INDEX Ref79 ON LAPTOP_INVENTARIO_F2_AHG_S1(STATUS_LAPTOP_ID)
;
-- 
-- INDEX: Ref217 
--

CREATE INDEX Ref217 ON SERVICIO_LAPTOP_F1_AHG_S1(SUCURSAL_ID)
;
-- 
-- INDEX: Ref13 
--

CREATE INDEX Ref13 ON SUCURSAL_TALLER_F1_AHG_S1(SUCURSAL_ID)
;
-- 
-- INDEX: Ref15 
--

CREATE INDEX Ref15 ON SUCURSAL_VENTA_F1_AHG_S1(SUCURSAL_ID)
;
