--@Autor: Karina Flores García 
--@Autor: Alejandro Herrera Gandarela
--@Fecha creación: 23/12/2021
--@Descripción: DDL para sitio N4
p
rompt Creando tablas para el sitio N3 en KFGBDD_S2

create or replace procedure drop_table_if_exists(name in varchar2) is
	v_count number;
begin
	select count(*) 
	into v_count 
	from all_tables 
	where table_name = name;
	
	if (v_count > 0) then
       		execute immediate 'drop table ' || name || ' cascade constraints';
	end if;
end;
/

declare
	v_tipo_procesador_r_kfg_s2 varchar2(30)     := 'TIPO_PROCESADOR_R_KFG_S2';
	v_tipo_tarjeta_video_r_kfg_s2 varchar2(30)	:= 'TIPO_TARJETA_VIDEO_R_KFG_S2';
	v_tipo_almacenamiento_r_kfg_s2 varchar2(30) := 'TIPO_ALMACENAMIENTO_R_KFG_S2';
	v_tipo_monitor_r_kfg_s2 varchar2(30)	    := 'TIPO_MONITOR_R_KFG_S2';
	v_laptop_f1_kfg_s2 varchar2(30) 	        := 'LAPTOP_F1_KFG_S2';
    v_laptop_f3_kfg_s2 varchar2(30) 	        := 'LAPTOP_F3_KFG_S2';
    v_sucursal_f4_kfg_s2 varchar2(30) 	        := 'SUCURSAL_F4_KFG_S2';
	v_status_laptop varchar2(30) 	            := 'STATUS_LAPTOP';
	v_sucursal_taller_f4_kfg_s2 varchar2(30) 	:= 'SUCURSAL_TALLER_F4_KFG_S2';
    v_sucursal_venta_f4_kfg_s2 varchar2(30) 	:= 'SUCURSAL_VENTA_F4_KFG_S2';
    v_servicio_laptop_f4_kfg_s2 varchar2(30) 	:= 'SERVICIO_LAPTOP_F4_KFG_S2';
begin
	drop_table_if_exists(v_tipo_procesador_r_kfg_s2);
	drop_table_if_exists(v_tipo_tarjeta_video_r_kfg_s2;
	drop_table_if_exists(v_tipo_almacenamiento_r_kfg_s2);
	drop_table_if_exists(v_tipo_monitor_r_kfg_s2);
	drop_table_if_exists(v_laptop_f1_kfg_s2);
	drop_table_if_exists(v_laptop_f3_kfg_s2);
	drop_table_if_exists(v_sucursal_f4_kfg_s2);
	drop_table_if_exists(v_status_laptop);
    drop_table_if_exists(v_sucursal_taller_f4_kfg_s2);
    drop_table_if_exists(v_sucursal_venta_f4_kfg_s2);
    drop_table_if_exists(v_servicio_laptop_f4_kfg_s2);
/

CREATE TABLE TIPO_PROCESADOR_R_KFG_S2(
    TIPO_PROCESADOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (TIPO_PROCESADOR_ID)
)
;



-- 
-- TABLE: TIPO_TARJETA_VIDEO_R_KFG_S2 
--

CREATE TABLE TIPO_TARJETA_VIDEO_R_KFG_S2(
    TIPO_TARJETA_VIDEO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                    VARCHAR2(40)     NOT NULL,
    DESCRIPCION              VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (TIPO_TARJETA_VIDEO_ID)
)
;



-- 
-- TABLE: TIPO_MONITOR_R_KFG_S2 
--

CREATE TABLE TIPO_MONITOR_R_KFG_S2(
    TIPO_MONITOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE              VARCHAR2(40)     NOT NULL,
    DESCRIPCION        VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (TIPO_MONITOR_ID)
)
;



-- 
-- TABLE: TIPO_ALMACENAMIENTO_R_KFG_S2 
--

CREATE TABLE TIPO_ALMACENAMIENTO_R_KFG_S2(
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                     VARCHAR2(40)     NOT NULL,
    DESCRIPCION               VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (TIPO_ALMACENAMIENTO_ID)
)
;



-- 
-- TABLE: LAPTOP_F1_KFG_S2 
--

CREATE TABLE LAPTOP_F1_KFG_S2(
    LAPTOP_ID                 NUMBER(10, 0)    NOT NULL,
    LAPTOP_REEMPLAZO_ID       NUMBER(10, 0)    NOT NULL,
    FOTO                      BLOB             NOT NULL,
    TIPO_PROCESADOR_ID        NUMBER(5, 0)     NOT NULL,
    TIPO_TARJETA_VIDEO_ID     NUMBER(5, 0)     NOT NULL,
    TIPO_MONITOR_ID           NUMBER(5, 0)     NOT NULL,
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (LAPTOP_ID), 
    CONSTRAINT RefTIPO_PROCESADOR_R_KFG_S213 FOREIGN KEY (TIPO_PROCESADOR_ID)
    REFERENCES TIPO_PROCESADOR_R_KFG_S2(TIPO_PROCESADOR_ID),
    CONSTRAINT RefTIPO_TARJETA_VIDEO_R_KFG_14 FOREIGN KEY (TIPO_TARJETA_VIDEO_ID)
    REFERENCES TIPO_TARJETA_VIDEO_R_KFG_S2(TIPO_TARJETA_VIDEO_ID),
    CONSTRAINT RefTIPO_MONITOR_R_KFG_S215 FOREIGN KEY (TIPO_MONITOR_ID)
    REFERENCES TIPO_MONITOR_R_KFG_S2(TIPO_MONITOR_ID),
    CONSTRAINT RefTIPO_ALMACENAMIENTO_R_KFG16 FOREIGN KEY (TIPO_ALMACENAMIENTO_ID)
    REFERENCES TIPO_ALMACENAMIENTO_R_KFG_S2(TIPO_ALMACENAMIENTO_ID)
)
;



-- 
-- TABLE: LAPTOP_F3_KFG_S2 
--

CREATE TABLE LAPTOP_F3_KFG_S2(
    LAPTOP_ID                 NUMBER(10, 0)     NOT NULL,
    LAPTOP_REEMPLAZO_ID       NUMBER(10, 0),
    NUM_SERIE                 VARCHAR2(18)      NOT NULL,
    CANTIDAD_RAM              NUMBER(6, 0)      NOT NULL,
    CARACTERISTICAS_EXTRAS    VARCHAR2(2000)    NOT NULL,
    TIPO_PROCESADOR_ID        NUMBER(5, 0)      NOT NULL,
    TIPO_TARJETA_VIDEO_ID     NUMBER(5, 0)      NOT NULL,
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)      NOT NULL,
    TIPO_MONITOR_ID           NUMBER(5, 0)      NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (LAPTOP_ID), 
    CONSTRAINT RefTIPO_PROCESADOR_R_KFG_S217 FOREIGN KEY (TIPO_PROCESADOR_ID)
    REFERENCES TIPO_PROCESADOR_R_KFG_S2(TIPO_PROCESADOR_ID),
    CONSTRAINT RefTIPO_TARJETA_VIDEO_R_KFG_18 FOREIGN KEY (TIPO_TARJETA_VIDEO_ID)
    REFERENCES TIPO_TARJETA_VIDEO_R_KFG_S2(TIPO_TARJETA_VIDEO_ID),
    CONSTRAINT RefTIPO_ALMACENAMIENTO_R_KFG19 FOREIGN KEY (TIPO_ALMACENAMIENTO_ID)
    REFERENCES TIPO_ALMACENAMIENTO_R_KFG_S2(TIPO_ALMACENAMIENTO_ID),
    CONSTRAINT RefTIPO_MONITOR_R_KFG_S220 FOREIGN KEY (TIPO_MONITOR_ID)
    REFERENCES TIPO_MONITOR_R_KFG_S2(TIPO_MONITOR_ID)
)
;



-- 
-- TABLE: SUCURSAL_F4_KFG_S2 
--

CREATE TABLE SUCURSAL_F4_KFG_S2(
    SUCURSAL_ID    NUMBER(10, 0)     NOT NULL,
    CLAVE          VARCHAR2(10)      NOT NULL,
    ES_TALLER      NUMBER(1, 0)      NOT NULL,
    ES_VENTA       NUMBER(1, 0)      NOT NULL,
    NOMBRE         VARCHAR2(40)      NOT NULL,
    LATITUD        BINARY_FLOAT      NOT NULL,
    LONGITUD       BINARY_FLOAT      NOT NULL,
    URL            VARCHAR2(2000)    NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (SUCURSAL_ID)
)
;



-- 
-- TABLE: SUCURSAL_TALLER_F4_KFG_S2 
--

CREATE TABLE SUCURSAL_TALLER_F4_KFG_S2(
    SUCURSAL_ID          NUMBER(10, 0)    NOT NULL,
    DIA_DESCANSO         NUMBER(1, 0)     NOT NULL,
    TELEFONO_ATENCION    VARCHAR2(20)     NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (SUCURSAL_ID), 
    CONSTRAINT RefSUCURSAL_F4_KFG_S21 FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F4_KFG_S2(SUCURSAL_ID)
)
;



-- 
-- TABLE: SERVICIO_LAPTOP_F4_KFG_S2 
--

CREATE TABLE SERVICIO_LAPTOP_F4_KFG_S2(
    NUM_SERVICIO    NUMBER(10, 0)     NOT NULL,
    LAPTOP_ID       NUMBER(10, 0)     NOT NULL,
    IMPORTE         NUMBER(8, 2)      NOT NULL,
    DIAGNOSTICO     VARCHAR2(2000)    NOT NULL,
    FACTURA         BLOB,
    SUCURSAL_ID     NUMBER(10, 0)     NOT NULL,
    CONSTRAINT PK10 PRIMARY KEY (NUM_SERVICIO, LAPTOP_ID), 
    CONSTRAINT RefSUCURSAL_TALLER_F4_KFG_S212 FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_TALLER_F4_KFG_S2(SUCURSAL_ID)
)
;



-- 
-- TABLE: STATUS_LAPTOP 
--

CREATE TABLE STATUS_LAPTOP(
    STATUS_LAPTOP_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE               VARCHAR2(40)     NOT NULL,
    DESCRIPCION         VARCHAR2(400)    NOT NULL,
    CONSTRAINT PK11 PRIMARY KEY (STATUS_LAPTOP_ID)
)
;



-- 
-- TABLE: SUCURSAL_VENTA_F4_KFG_S2 
--

CREATE TABLE SUCURSAL_VENTA_F4_KFG_S2(
    SUCURSAL_ID      NUMBER(10, 0)    NOT NULL,
    HORA_APERTURA    DATE             NOT NULL,
    HORA_CIERRE      DATE             NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (SUCURSAL_ID), 
    CONSTRAINT RefSUCURSAL_F4_KFG_S22 FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F4_KFG_S2(SUCURSAL_ID)
)
;



-- 
-- INDEX: Ref613 
--

CREATE INDEX Ref613 ON LAPTOP_F1_KFG_S2(TIPO_PROCESADOR_ID)
;
-- 
-- INDEX: Ref714 
--

CREATE INDEX Ref714 ON LAPTOP_F1_KFG_S2(TIPO_TARJETA_VIDEO_ID)
;
-- 
-- INDEX: Ref915 
--

CREATE INDEX Ref915 ON LAPTOP_F1_KFG_S2(TIPO_MONITOR_ID)
;
-- 
-- INDEX: Ref816 
--

CREATE INDEX Ref816 ON LAPTOP_F1_KFG_S2(TIPO_ALMACENAMIENTO_ID)
;
-- 
-- INDEX: Ref617 
--

CREATE INDEX Ref617 ON LAPTOP_F3_KFG_S2(TIPO_PROCESADOR_ID)
;
-- 
-- INDEX: Ref718 
--

CREATE INDEX Ref718 ON LAPTOP_F3_KFG_S2(TIPO_TARJETA_VIDEO_ID)
;
-- 
-- INDEX: Ref819 
--

CREATE INDEX Ref819 ON LAPTOP_F3_KFG_S2(TIPO_ALMACENAMIENTO_ID)
;
-- 
-- INDEX: Ref920 
--

CREATE INDEX Ref920 ON LAPTOP_F3_KFG_S2(TIPO_MONITOR_ID)
;
-- 
-- INDEX: Ref212 
--

CREATE INDEX Ref212 ON SERVICIO_LAPTOP_F4_KFG_S2(SUCURSAL_ID)
;
-- 
-- INDEX: Ref11 
--

CREATE INDEX Ref11 ON SUCURSAL_TALLER_F4_KFG_S2(SUCURSAL_ID)
;
-- 
-- INDEX: Ref12 
--

CREATE INDEX Ref12 ON SUCURSAL_VENTA_F4_KFG_S2(SUCURSAL_ID)
;
