--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      KAR
-- Project :      Nodo4.DM1
-- Author :       KAR
--
-- Date Created : Sunday, January 09, 2022 19:47:19
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: TIPO_PROCESADOR_R_KFG_S2 
--

CREATE TABLE TIPO_PROCESADOR_R_KFG_S2(
    TIPO_PROCESADOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_PROCESADOR_R_KFG_S2_PK PRIMARY KEY (TIPO_PROCESADOR_ID)
)
;



-- 
-- TABLE: TIPO_TARJETA_VIDEO_R_KFG_S2 
--

CREATE TABLE TIPO_TARJETA_VIDEO_R_KFG_S2(
    TIPO_TARJETA_VIDEO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                    VARCHAR2(40)     NOT NULL,
    DESCRIPCION              VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_TARJETA_VIDEO_R_KFG_S2_PK PRIMARY KEY (TIPO_TARJETA_VIDEO_ID)
)
;



-- 
-- TABLE: TIPO_MONITOR_R_KFG_S2 
--

CREATE TABLE TIPO_MONITOR_R_KFG_S2(
    TIPO_MONITOR_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE              VARCHAR2(40)     NOT NULL,
    DESCRIPCION        VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_MONITOR_R_KFG_S2_PK PRIMARY KEY (TIPO_MONITOR_ID)
)
;



-- 
-- TABLE: TIPO_ALMACENAMIENTO_R_KFG_S2 
--

CREATE TABLE TIPO_ALMACENAMIENTO_R_KFG_S2(
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE                     VARCHAR2(40)     NOT NULL,
    DESCRIPCION               VARCHAR2(400)    NOT NULL,
    CONSTRAINT TIPO_ALMACENAMIENTO_R_KFG_S2_PK PRIMARY KEY (TIPO_ALMACENAMIENTO_ID)
)
;



-- 
-- TABLE: LAPTOP_F1_KFG_S2 
--

CREATE TABLE LAPTOP_F1_KFG_S2(
    LAPTOP_ID                 NUMBER(10, 0)    NOT NULL,
    LAPTOP_REEMPLAZO_ID       NUMBER(10, 0)    NOT NULL,
    FOTO                      BLOB             NOT NULL,
    TIPO_PROCESADOR_ID        NUMBER(5, 0)     NOT NULL,
    TIPO_TARJETA_VIDEO_ID     NUMBER(5, 0)     NOT NULL,
    TIPO_MONITOR_ID           NUMBER(5, 0)     NOT NULL,
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    CONSTRAINT LAPTOP_F1_KFG_S2_PK PRIMARY KEY (LAPTOP_ID), 
    CONSTRAINT TIPO_PROCESADOR_R_KFG_S2_FK FOREIGN KEY (TIPO_PROCESADOR_ID)
    REFERENCES TIPO_PROCESADOR_R_KFG_S2(TIPO_PROCESADOR_ID) ON DELETE cascade,
    CONSTRAINT TIPO_TARJETA_VIDEO_R_KFG_S2_FK FOREIGN KEY (TIPO_TARJETA_VIDEO_ID)
    REFERENCES TIPO_TARJETA_VIDEO_R_KFG_S2(TIPO_TARJETA_VIDEO_ID) ON DELETE cascade,
    CONSTRAINT TIPO_MONITOR_R_KFG_S2_FK FOREIGN KEY (TIPO_MONITOR_ID)
    REFERENCES TIPO_MONITOR_R_KFG_S2(TIPO_MONITOR_ID) ON DELETE cascade,
    CONSTRAINT TIPO_ALMACENAMIENTO_R_KFG_S2_FK FOREIGN KEY (TIPO_ALMACENAMIENTO_ID)
    REFERENCES TIPO_ALMACENAMIENTO_R_KFG_S2(TIPO_ALMACENAMIENTO_ID) ON DELETE cascade
)
;



-- 
-- TABLE: LAPTOP_F3_KFG_S2 
--

CREATE TABLE LAPTOP_F3_KFG_S2(
    LAPTOP_ID                 NUMBER(10, 0)     NOT NULL,
    LAPTOP_REEMPLAZO_ID       NUMBER(10, 0),
    NUM_SERIE                 VARCHAR2(18)      NOT NULL,
    CANTIDAD_RAM              NUMBER(6, 0)      NOT NULL,
    CARACTERISTICAS_EXTRAS    VARCHAR2(2000)    NOT NULL,
    TIPO_PROCESADOR_ID        NUMBER(5, 0)      NOT NULL,
    TIPO_TARJETA_VIDEO_ID     NUMBER(5, 0)      NOT NULL,
    TIPO_ALMACENAMIENTO_ID    NUMBER(5, 0)      NOT NULL,
    TIPO_MONITOR_ID           NUMBER(5, 0)      NOT NULL,
    CONSTRAINT LAPTOP_F3_KFG_S2_PK PRIMARY KEY (LAPTOP_ID), 
    CONSTRAINT TIPO_PROCESADOR_R_KFG_S2_FK FOREIGN KEY (TIPO_PROCESADOR_ID)
    REFERENCES TIPO_PROCESADOR_R_KFG_S2(TIPO_PROCESADOR_ID) ON DELETE cascade,
    CONSTRAINT TIPO_TARJETA_VIDEO_R_KFG_S2_FK FOREIGN KEY (TIPO_TARJETA_VIDEO_ID)
    REFERENCES TIPO_TARJETA_VIDEO_R_KFG_S2(TIPO_TARJETA_VIDEO_ID) ON DELETE cascade,
    CONSTRAINT TIPO_ALMACENAMIENTO_R_KFG_S2_FK FOREIGN KEY (TIPO_ALMACENAMIENTO_ID)
    REFERENCES TIPO_ALMACENAMIENTO_R_KFG_S2(TIPO_ALMACENAMIENTO_ID) ON DELETE cascade,
    CONSTRAINT TIPO_MONITOR_R_KFG_S2_FK FOREIGN KEY (TIPO_MONITOR_ID)
    REFERENCES TIPO_MONITOR_R_KFG_S2(TIPO_MONITOR_ID) ON DELETE cascade
)
;



-- 
-- TABLE: SUCURSAL_F4_KFG_S2 
--

CREATE TABLE SUCURSAL_F4_KFG_S2(
    SUCURSAL_ID    NUMBER(10, 0)     NOT NULL,
    CLAVE          VARCHAR2(10)      NOT NULL,
    ES_TALLER      NUMBER(1, 0)      NOT NULL,
    ES_VENTA       NUMBER(1, 0)      NOT NULL,
    NOMBRE         VARCHAR2(40)      NOT NULL,
    LATITUD        BINARY_FLOAT      NOT NULL,
    LONGITUD       BINARY_FLOAT      NOT NULL,
    URL            VARCHAR2(2000)    NOT NULL,
    CONSTRAINT SUCURSAL_F4_KFG_S2_PK PRIMARY KEY (SUCURSAL_ID)
)
;



-- 
-- TABLE: SUCURSAL_TALLER_F4_KFG_S2 
--

CREATE TABLE SUCURSAL_TALLER_F4_KFG_S2(
    SUCURSAL_ID          NUMBER(10, 0)    NOT NULL,
    DIA_DESCANSO         NUMBER(1, 0)     NOT NULL,
    TELEFONO_ATENCION    VARCHAR2(20)     NOT NULL,
    CONSTRAINT SUCURSAL_TALLER_F4_KFG_S2_PK PRIMARY KEY (SUCURSAL_ID), 
    CONSTRAINT SUCURSAL_F4_KFG_S2_FK FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F4_KFG_S2(SUCURSAL_ID) ON DELETE cascade
)
;



-- 
-- TABLE: SERVICIO_LAPTOP_F4_KFG_S2 
--

CREATE TABLE SERVICIO_LAPTOP_F4_KFG_S2(
    NUM_SERVICIO    NUMBER(10, 0)     NOT NULL,
    LAPTOP_ID       NUMBER(10, 0)     NOT NULL,
    IMPORTE         NUMBER(8, 2)      NOT NULL,
    DIAGNOSTICO     VARCHAR2(2000)    NOT NULL,
    FACTURA         BLOB,
    SUCURSAL_ID     NUMBER(10, 0)     NOT NULL,
    CONSTRAINT SERVICIO_LAPTOP_F4_KFG_S2_PK PRIMARY KEY (NUM_SERVICIO, LAPTOP_ID), 
    CONSTRAINT SUCURSAL_TALLER_F4_KFG_S2_FK FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_TALLER_F4_KFG_S2(SUCURSAL_ID) ON DELETE cascade,
    CONSTRAINT LAPTOP_F1_KFG_S2_FK FOREIGN KEY (LAPTOP_ID)
    REFERENCES LAPTOP_F1_KFG_S2(LAPTOP_ID) ON DELETE cascade
)
;



-- 
-- TABLE: STATUS_LAPTOP 
--

CREATE TABLE STATUS_LAPTOP(
    STATUS_LAPTOP_ID    NUMBER(5, 0)     NOT NULL,
    CLAVE               VARCHAR2(40)     NOT NULL,
    DESCRIPCION         VARCHAR2(400)    NOT NULL,
    CONSTRAINT STATUS_LAPTOP_PK PRIMARY KEY (STATUS_LAPTOP_ID)
)
;



-- 
-- TABLE: SUCURSAL_VENTA_F4_KFG_S2 
--

CREATE TABLE SUCURSAL_VENTA_F4_KFG_S2(
    SUCURSAL_ID      NUMBER(10, 0)    NOT NULL,
    HORA_APERTURA    DATE             NOT NULL,
    HORA_CIERRE      DATE             NOT NULL,
    CONSTRAINT SUCURSAL_VENTA_F4_KFG_S2_PK PRIMARY KEY (SUCURSAL_ID), 
    CONSTRAINT SUCURSAL_F4_KFG_S2_FK FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F4_KFG_S2(SUCURSAL_ID) ON DELETE cascade
)
;



-- 
-- INDEX: Ref613 
--

CREATE INDEX Ref613 ON LAPTOP_F1_KFG_S2(TIPO_PROCESADOR_ID)
;
-- 
-- INDEX: Ref714 
--

CREATE INDEX Ref714 ON LAPTOP_F1_KFG_S2(TIPO_TARJETA_VIDEO_ID)
;
-- 
-- INDEX: Ref915 
--

CREATE INDEX Ref915 ON LAPTOP_F1_KFG_S2(TIPO_MONITOR_ID)
;
-- 
-- INDEX: Ref816 
--

CREATE INDEX Ref816 ON LAPTOP_F1_KFG_S2(TIPO_ALMACENAMIENTO_ID)
;
-- 
-- INDEX: Ref617 
--

CREATE INDEX Ref617 ON LAPTOP_F3_KFG_S2(TIPO_PROCESADOR_ID)
;
-- 
-- INDEX: Ref718 
--

CREATE INDEX Ref718 ON LAPTOP_F3_KFG_S2(TIPO_TARJETA_VIDEO_ID)
;
-- 
-- INDEX: Ref819 
--

CREATE INDEX Ref819 ON LAPTOP_F3_KFG_S2(TIPO_ALMACENAMIENTO_ID)
;
-- 
-- INDEX: Ref920 
--

CREATE INDEX Ref920 ON LAPTOP_F3_KFG_S2(TIPO_MONITOR_ID)
;
-- 
-- INDEX: Ref212 
--

CREATE INDEX Ref212 ON SERVICIO_LAPTOP_F4_KFG_S2(SUCURSAL_ID)
;
-- 
-- INDEX: Ref11 
--

CREATE INDEX Ref11 ON SUCURSAL_TALLER_F4_KFG_S2(SUCURSAL_ID)
;
-- 
-- INDEX: Ref12 
--

CREATE INDEX Ref12 ON SUCURSAL_VENTA_F4_KFG_S2(SUCURSAL_ID)
;
